### ISSUE TITLE
Unable to pull from imagestream

### ISSUE THREAD

**Issue by tibcoplord** [openshift/windows-machine-config-bootstrapper#211]
With this configuration on azure, I found pulling from the ImageStream didn't work.   I see -

```
$ oc describe pod pmml-scoring-service-77757499d7-qqjnq
...
Events:
  Type     Reason     Age                From                      Message
  ----     ------     ----               ----                      -------
  Normal   Scheduled  <unknown>          default-scheduler         Successfully assigned default/pmml-scoring-service-77757499d7-qqjnq to winworker-svad8
  Warning  Failed     27s (x3 over 54s)  kubelet, winworker-svad8  Back-off pulling image "image-registry.openshift-image-registry.svc:5000/default/scoring-service-base-win:latest"
  Normal   Pulling    12s (x3 over 54s)  kubelet, winworker-svad8  Pulling image "image-registry.openshift-image-registry.svc:5000/default/scoring-service-base-win:latest"
  Warning  Failed     12s (x3 over 54s)  kubelet, winworker-svad8  Failed to pull image "image-registry.openshift-image-registry.svc:5000/default/scoring-service-base-win:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://image-registry.openshift-image-registry.svc:5000/v2/: dial tcp: lookup image-registry.openshift-image-registry.svc: no such host
```

However I found the following did work -

* login to windows server
* add _public imagestream address_ to C:\PrograData\doker\config\daemon.json as an insecure registry
* Restart-Service \*docker\*
* docker login ... _public imagestream address_
* docker pull _public imagestream address_/default/scoring-service-base-win:latest
* docker tag _public imagestream address_/default/scoring-service-base-win:latest scoring-service-base-win:latest
* update the yaml to use image address scoring-service-base-win:latest

It would be good to know if this configuration is designed to use the ImageStream, or if there is a way to push a image to the windows server.

Thanks !

**Comment by tibcoplord** [comment]
I have found that using an IP address of the ImageStream server can be made to work - this requires also adding the ImageStream IP address to the daemon.json file on the windows node.

So this seems to be a DNS issue + authentication.

**Comment by aravindhp** [comment]
We have moved away from the Ansible playbook to an [operator](https://www.openshift.com/blog/announcing-the-community-windows-machine-config-operator-on-openshift-4.6) model. Please reproduce this issue with the  and we will take a look if it still persists.

**Comment by rarguello** [comment]
I can confirm this bug still happens on **OpenShift 4.7.9** (IPI on vSphere) with the **Windows Machine Config Operator 2.0.0**:

```
Error response from daemon: Get https://image-registry.openshift-image-registry.svc:5000/v2/: dial tcp: lookup image-registry.openshift-image-registry.svc: no such host
```

If you use the IP address of the OpenShift Registry it can reach it, but now gives an "x509 certificate signed by unknown authority" error!


**Workaround:**

- Get the IP address of the OpenShift Registry:

```
$ oc get service/image-registry -n openshift-image-registry -o jsonpath='{.spec.clusterIP}'
```

- Add the IP address and hostname of the Registry to the "hosts" file on the Windows instance (your IP address should be different):

```
PS C:\> $DesiredIP="172.30.227.178"
PS C:\> $Hostname="image-registry.openshift-image-registry.svc"
PS C:\> $hostsFilePath = "$($Env:WinDir)\system32\Drivers\etc\hosts"
PS C:\> Add-Content -Encoding UTF8 $hostsFilePath "$DesiredIP $Hostname"
```

- Get the Registry certificate:

```
$ oc get configmap image-registry-certificates -n openshift-image-registry -o jsonpath='{.data.image-registry\.openshift-image-registry\.svc\.\.5000}'
```

- Add the Registry certificate to the Docker "certs.d" directory on the Windows instance, for Docker to trust the registry (using Vim installed with Choco here):

```
PS C:\> mkdir C:\ProgramData\docker\certs.d\image-registry.openshift-image-registry.svc5000\
PS C:\> vim.exe C:\ProgramData\docker\certs.d\image-registry.openshift-image-registry.svc5000\registry.crt
```

Why the directory has to be called _image-registry.openshift-image-registry.svc5000_?
https://github.com/moby/moby/blob/12c67f42d85103c57c14f27579ff46fccdc3ee07/registry/config_windows.go

NOTE: Having a _insecure-registries_ config on Docker also works, but is *not secure*:

```
PS C:\> mkdir C:\ProgramData\Docker\config\
PS C:\> vim.exe C:\ProgramData\Docker\config\daemon.json
```

daemon.json:
```
{ "insecure-registries": ["image-registry.openshift-image-registry.svc:5000"] }
```

- Restart Docker

```
PS C:\> Restart-Service docker -f
```

Ideally, all these changes should be done on the Windows template you need to create to use Windows Containers.

**Comment by rarguello** [comment]
I found the reason for this bug:

**My Windows node cannot access my services using the service IP**
https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems#my-windows-node-cannot-access-my-services-using-the-service-ip
