### ISSUE TITLE
Ansible issue when worker nodes have common string in the IP

### ISSUE THREAD

**Issue by bejoycalias** [openshift/windows-machine-config-bootstrapper#219]
I have a set of a OpenShift worker nodes with IPs 192.168.200.2, 192.168.200.22, 192.168.200.234 etc. where '192.168.200.2' is a common string in all the IP addresses.

Due to this, the below line in windows-machine-config-bootstrapper/tools/ansible/tasks/wsu/main.yaml (line 329) breaks the ansible automation, since the output of it contains multiple nodes, not just the node I am trying to bootstrap.
`shell: "oc get node -o wide |awk '/{{ inventory_hostname }}/ || /{{ private_ip }}/ {print $1}'"`

For example, I am trying to bootstrap a Windows node with 192.168.200.2 IP. But since I have other nodes with this common string in the IP address, the ansible steps fails because it outputs all the nodes with similar IP addresses.

If I run above command, 
```
# oc get node -o wide |awk '/192.168.200.2/ || /192.168.200.2/ {print $1}'
win2k19dc
worker-00
worker-01
worker-02
```
It was supposed to show only the node 'win2k19dc' where I was trying to bootstrap. But it shows the other 3 nodes which also has '192.168.200.2' in the beginning of the IP.

As a workaround I modified the line to have a space in the end, not sure if this is the right way.
`shell: "oc get node -o wide |awk '/{{ inventory_hostname }} / || /{{ private_ip }} / {print $1}'"`

**Comment by aravindhp** [comment]
We are no longer developing the Ansible playbook and have moved to an [operator model](https://www.openshift.com/blog/announcing-the-community-windows-machine-config-operator-on-openshift-4.6).
